# Build aşaması
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

COPY ["MyCryptoTracker.csproj", "./"]
RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o out

# Çalıştırma aşaması
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/out .

RUN chmod -R 777 /app

ENTRYPOINT ["dotnet", "MyCryptoTracker.dll"]